resolver: lts-13.30
pvp-bounds: both
packages:
  - .
extra-deps:
  - config-ini-0.2.4.0
  - data-clist-0.1.2.3
  - text-zipper-0.10.1
  - word-wrap-0.4.1
  - brick-0.47.1
  - ../../merkle-shit/merkle-schemes/merkle-schemes-higher
# - ../../merkle-shit/merkle-schemes/merkle-schemes-higher-ext
